PUMP_DISCHARGE_SPEED = int(1)  # mL/s

PIN_BUTTON_LEFT_TOP = 12
PIN_BUTTON_LEFT_MIDDLE = 9
PIN_BUTTON_LEFT_BOTTOM = 11
PIN_BUTTON_RIGHT_TOP = 26
PIN_BUTTON_RIGHT_MIDDLE = 19
PIN_BUTTON_RIGHT_BOTTOM = 13