PUMP_DISCHARGE_SPEED = float(0.1)  # L/s

PIN_BUTTON_LEFT_TOP = 24
PIN_BUTTON_LEFT_MIDDLE = 23
PIN_BUTTON_LEFT_BOTTOM = 18
PIN_BUTTON_RIGHT_TOP = 17
PIN_BUTTON_RIGHT_MIDDLE = 27
PIN_BUTTON_RIGHT_BOTTOM = 22