FONT_DISPLAY_1_BOLD = ("Poppins", 79, "bold")
FONT_HEADING_1_REGULAR = ("Poppins", 59)
FONT_HEADING_1_BOLD = ("Poppins", 59, "bold")
FONT_HEADING_2_REGULAR = ("Poppins", 44)
FONT_HEADING_2_BOLD = ("Poppins", 44, "bold")
FONT_HEADING_3_REGULAR = ("Poppins", 33)
FONT_HEADING_3_BOLD = ("Poppins", 33, "bold")
FONT_BODY_REGULAR = ("Poppins", 35)

FONT_BUTTON_DECORATION = ("Poppins", 16)

DISTANCE_BETWEEN_MENU = 100
DISTANCE_BETWEEN_MENU_SMALL = 64

COLOR_BLUE = "#00A0F3"
COLOR_WHITE = "#FFFFFF"

PADDING_FROM_FRAME = 48